name: Convert MD to PDF and Create Release

on: 
  push:

jobs:
  convert_via_pandoc:
    name: Convert all with pandoc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pandoc
        run: |
          sudo apt update
          sudo apt install pandoc texlive-latex-recommended
      
      - name: Run pandoc
        run: |
          mkdir output
          for file in *.md; do
            pandoc -o "output/${file%.md}.pdf" "$file"
          done
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output
